### PR TITLE
Bug 1271053 - Flame transition build added r=gerard-majax

### PR DESCRIPTION
**Pull request by TitanNano**

### CODE REVIEW

**Comment by autonome** [comment]
When will this ship in b2g-installer addon?

**Comment by TitanNano** [comment]
@autonome if you have the addon installed in your firefox you can already download the build.
The build info is fetched everytime you load about:b2g-installer

**Comment by ghost** [comment]
Hm, it doesn't show up. It says no builds available for Flame.

**Comment by TitanNano** [comment]
@boot2geckoicon in that case, connect your flame and refresh the page a couple of times. It's a little buggy sometimes. but it should show you three builds.

**Comment by ghost** [comment]
ok i'll try, thanks!

**Pull request merged**
